# Simulation settings
simulation_fps  : 240
physics_fps     : 30
gravity         : -9.80665


# Joint direction configuration
joint_config:
  l_sho_roll    : 1
  l_sho_pitch   : 1
  l_el          : 1
  l_hip_yaw     : 1
  l_hip_roll    : 1
  l_hip_pitch   : 1
  l_knee        : 1
  l_ank_pitch   : 1
  l_ank_roll    : 1
  r_sho_roll    : 1
  r_sho_pitch   : 1
  r_el          : 1
  r_hip_yaw     : 1
  r_hip_roll    : 1
  r_hip_pitch   : 1
  r_knee        : 1
  r_ank_pitch   : 1
  r_ank_roll    : 1
  head_pan      : 1
  head_tilt     : 1
